version: 2
updates:
  -
    # Maintain dependencies for GitHub Actions
    package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "config: "
  -
    # Maintain python dependencies
    package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    commit-message:
      prefix: "config: "
