name = "main-blog"
compatibility_date = "2025-12-29"

[assets]
directory = "./output"
html_handling = "auto-trailing-slash"
# not_found_handling accepted values: "single-page-application" | "404-page" | "none" (default "none")
# https://developers.cloudflare.com/workers/wrangler/configuration/#assets
not_found_handling = "404-page"
