---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'git revision'
        required: false
        default: ''

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: '${{ github.event.inputs.git_rev }}'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "latest"

      - name: Install dependencies
        run: |
          uv --version
          uv sync

      - name: Check Python coding style
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            uv run inv style --rev-range "${{ github.event.before }}..${{ github.sha }}"
          else
            uv run inv style
          fi

      - name: Check whether pelican local pages is buildable
        run: |
          uv run inv build

      - name: Check whether pelican public pages and search index are buildable
        run: |
          uv run inv build-publish --build-pagefind

      - name: Check Python dependencies through pip-audit
        run: |
          uv run inv security-check
