---
name: New pull request received

on:
  pull_request:
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'git revision'
        required: false
        default: ''

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: '${{ github.event.inputs.git_rev }}'

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U pip uv
          uv sync

      - name: Check Python coding style
        run: |
          uv run inv style

      - name: Check whether pelican local pages is buildable
        run: |
          uv run inv build

      - name: Check whether pelican public pages is buildable
        run: |
          uv run inv build-publish
